### ISSUE TITLE
change for Readme

### ISSUE THREAD

**Issue by globian** [bariew/yii2-log-module#1]
Hallo Pavel, к сожалению после того как актуализировал твой Модуль не работает ничего, всё слетело, вероятно надо и Readme  изменить, смотрел твои изменения последнего коммита, то наверное вызов будет такoй 'class' => 'bariew\logModule\LogModule'

**Comment by bariew** [comment]
Привет! Да, я сейчас серьезно переделываю модуль, для стабильной работы используйте версию 1.0.0

**Comment by bariew** [comment]
Ок, слишком серьезные изменения, буду другой модуль делать, этот откатил
